/*
Name: Sajid Abdullah
Date: 17 June, 2026

Description: The program opens up with a menu screen that has three buttons,
play, help, and exit. If you click help it takes you to a help screen that shows the game
instructions, and you can either go back to the menu or jump straight into the game from
there. When you click play it opens up the actual game. Two paddles and a ball spawn on
the screen and the timer starts running every 16 milliseconds, and that is what moves the
ball and checks all the collisions with the paddles, the walls, and any powerups on
screen. Every time a paddle hits the ball the streak goes up, and once it hits a multiple
of 4 (4, 8, 12,...) a powerup spawns somewhere random on the screen. When the ball then hits that
powerup, whichever player hit the ball last gets the effect, which is either a speed
boost for their paddle, a speed reduction on the opponent's paddle, or a size increase
for their paddle. The powerup gets cleared when the next one spawns. Once a player
reaches 7 points the game stops, the music switches to a win sound, and a win screen
pops up with play again, menu, and exit buttons. At any time during the game you can
press escape to pause, which brings up a resume, menu, and exit screen.

Resources: Paddle and ball images from https://github.com/nuno-faria/pong-game,
Rest of the images generated by ChatGPT
Teacher templates and examples:
https://docs.google.com/document/d/1pSsqMMKXSzFDfD8bOZad_qHnRzTZaN9Hkjtkd9xAi-k - menu/help/game structure, hover buttons, music with Clip
https://docs.google.com/document/d/1g72iNFqF2EjVicGbMbL4XZmvNEsJZ4D3VSeM5741exw - timer, paddle movement with booleans, boundary clamping
https://docs.google.com/document/d/1_0BpXWV-f5p9NSlgFeG_8oceVwvEiuUxB6ew5fuoNq4 - pause menu
External resources:
https://riptutorial.com/java/example/612/play-an-audio-file-looped - Clip.LOOP_CONTINUOUSLY for background music looping
https://docs.oracle.com/javase/7/docs/api/javax/sound/sampled/Clip.html - setMicrosecondPosition for restarting music on play again
*/
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.sound.sampled.*;
import java.io.File;

public class main extends JPanel implements MouseListener, MouseMotionListener {

    int mouseX = 0;
    int mouseY = 0;
    Image bg = new ImageIcon("menu.png").getImage();
    Clip music;
    public main() {
        setPreferredSize(new Dimension(1300, 700));
        addMouseListener(this);
        addMouseMotionListener(this);
        //play menu music
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File("menu_music.wav"));
            music = AudioSystem.getClip();
            music.open(audio);
            music.loop(Clip.LOOP_CONTINUOUSLY);
        } catch (Exception e) {
            System.out.println("Music file not found.");
        }
    }
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(bg, 0, 0, 1300, 700, this);

        g.setFont(new Font("Courier New", Font.BOLD, 40));

        //play button (center)
        if (mouseX > 500 && mouseX < 800 && mouseY > 230 && mouseY < 300) {
            g.setColor(Color.WHITE);
        } else {
            g.setColor(Color.BLACK);
        }
        g.fillRect(500, 230, 300, 70);
        g.setColor(Color.WHITE);
        g.drawRect(500, 230, 300, 70);
        if (mouseX > 500 && mouseX < 800 && mouseY > 230 && mouseY < 300) {
            g.setColor(Color.BLACK);
        } else {
            g.setColor(Color.WHITE);
        }
        g.drawString("PLAY", 603, 277);

        //help button (center)
        if (mouseX > 500 && mouseX < 800 && mouseY > 340 && mouseY < 410) {
            g.setColor(Color.WHITE);
        } else {
            g.setColor(Color.BLACK);
        }
        g.fillRect(500, 340, 300, 70);
        g.setColor(Color.WHITE);
        g.drawRect(500, 340, 300, 70);
        if (mouseX > 500 && mouseX < 800 && mouseY > 340 && mouseY < 410) {
            g.setColor(Color.BLACK);
        } else {
            g.setColor(Color.WHITE);
        }
        g.drawString("HELP", 603, 387);

        //exit button (center)
        if (mouseX > 500 && mouseX < 800 && mouseY > 450 && mouseY < 520) {
            g.setColor(Color.WHITE);
        } else {
            g.setColor(Color.BLACK);
        }
        g.fillRect(500, 450, 300, 70);
        g.setColor(Color.WHITE);
        g.drawRect(500, 450, 300, 70);
        if (mouseX > 500 && mouseX < 800 && mouseY > 450 && mouseY < 520) {
            g.setColor(Color.BLACK);
        } else {
            g.setColor(Color.WHITE);
        }
        g.drawString("EXIT", 603, 497);
    }

    public void mousePressed(MouseEvent e) {
        int x = e.getX();
        int y = e.getY();

        //play button
        if (x > 500 && x < 800 && y > 230 && y < 300) {
            if (music != null) {
                music.stop();
            }
            game xy = new game();
            JFrame gameWindow = new JFrame("Game");
            gameWindow.add(xy);
            gameWindow.setUndecorated(true);
            gameWindow.pack();
            gameWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            gameWindow.setLocationRelativeTo(null);
            gameWindow.setVisible(true);
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            currentFrame.dispose();
        }

        //help button
        if (x > 500 && x < 800 && y > 340 && y < 410) {
            if (music != null) {
                music.stop();
            }
            help xy = new help();
            JFrame gameWindow = new JFrame("Help");
            gameWindow.add(xy);
            gameWindow.setUndecorated(true);
            gameWindow.pack();
            gameWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            gameWindow.setLocationRelativeTo(null);
            gameWindow.setVisible(true);
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
            currentFrame.dispose();
        }

        //exit button
        if (x > 500 && x < 800 && y > 450 && y < 520) {
            System.exit(0);
        }
    }

    //mouse movement
    public void mouseMoved(MouseEvent e) {
        mouseX = e.getX();
        mouseY = e.getY();
        repaint();
    }
    public void mouseDragged(MouseEvent e) {
    }
    public void mouseReleased(MouseEvent e) {
    }
    public void mouseClicked(MouseEvent e) {
    }
    public void mouseEntered(MouseEvent e) {
    }
    public void mouseExited(MouseEvent e) {
    }
    public static void main(String[] args) {

        JFrame window = new JFrame("Menu");

        main menu = new main();

        window.add(menu);
        window.setUndecorated(true);
        window.pack();

        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setLocationRelativeTo(null);
        window.setVisible(true);
    }
}